
import Head from 'next/head';
import ContactJumbo from '../components/views/contact/ContactJumbo';
import ContactSection from '../components/views/contact/ContactSection';
import AppLayout from './../components/layout/AppLayout';

export default function contact() {
  return (
    <>
      <Head>
        <title>Contactez-Nous | Centre Mohammed VI de traitement du cancer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico" />
      </Head>

      <AppLayout>
        <ContactJumbo />
        <ContactSection />
        {/* <GoogleMapIframe addClass="xl:w-6/12 h-72" /> */}
      </AppLayout>

    </>
  )
}
