import Head from 'next/head'
import AppLayout from './../components/layout/AppLayout'
import Jumbo from '../components/views/home/Jumbo'
import SpecialitySection from '../components/views/speciality/SpecialitySection'
import CareSection from '../components/views/cares/CareSection'
import PartnerSection from '../components/views/partner/PartnerSection'
import NewsSection from '../components/views/news/NewsSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Accueil | Centre Mohammed VI de traitement du cancer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico" />
      </Head>

      <AppLayout>
        <Jumbo />
        <SpecialitySection />
        <CareSection />
        <PartnerSection />
        <NewsSection />
      </AppLayout>

    </>
  )
}
