
import AppLayout from '../components/layout/AppLayout';
import Head from 'next/head';
import PresentJumbo from '../components/views/present/PresentJumbo';
import PresentDetails from '../components/views/present/PresentDetails';

export default function WhoWeAre() {
  return (
    <>
      <Head>
        <title>Présentation | Centre mohammed VI pour le traitement des cancers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico" />
      </Head>

      <AppLayout>
        <PresentJumbo />
        <PresentDetails />
      </AppLayout>
    </>
  )

}