import SpecialityJumbo from "../components/views/speciality/SpecialityJumbo"
import Head from 'next/head';
import AppLayout from './../components/layout/AppLayout';
import SpecialityDetails from "../components/views/speciality/SpecialityDetails";



const SpecialityPage = () => {
  return (
    <>
      <Head>
        <title>Nos Specialités | Centre Mohammed VI de traitement du cancer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico" />
      </Head>

      <AppLayout>
        <SpecialityJumbo />
        <SpecialityDetails />
      </AppLayout>
    </>
  )
}

export default SpecialityPage
